### ISSUE TITLE
sanitize_filepath: "./" is unnecessarily modified when platform="Linux"

### ISSUE THREAD

**Issue by ProfElectric** [thombashi/pathvalidate#13]
If you pass ./whatever/path to sanitize_filepath, "./" is changed to "._/"

Since "./" != "._/" on any platform this will cause code using pathvalidate to throw an exception down the line.

**Comment by thombashi** [comment]
@ProfElectric 
Thank you for your report.

I had fixed the issue at `pathvalidate 2.3.0`.
Please try to upgrade the package.
