### ISSUE TITLE
validate_filename() and sanitize_filename() pass '.' and '..'

### ISSUE THREAD

**Issue by mkbloke** [thombashi/pathvalidate#19]
In pathvalidate 2.4.1:
```
>>> pathvalidate.validate_filename(".")
>>> pathvalidate.validate_filename("..")
>>> pathvalidate.sanitize_filename(".")
'.'
>>> pathvalidate.sanitize_filename("..")
'..'
```
I know that `.` and `..` can be valid in a path, but surely not as filenames on any of the supported platforms?

Thanks.

Edited to add:

My expectation would be that `validate_filename()` would perhaps raise a ValidationError with a reason of `RESERVED_NAME` in the two cases above?

Also, if these are considered reserved filenames, shouldn't `_` be appended to each, as with, for example: `sanitize_filename("con")` returns `con_`?

**Comment by blerrgh** [comment]
Was this ever resolved?  I have the same issue in 2.5.2

It would be great if `sanitize_filename("..")`  (or maybe `sanitize_filename("..", check_return=True)`) returned "`_`"

**Comment by thombashi** [comment]
I have considered this previously and concluded that it is difficult to apply replacements unconditionally.
Unlike other reserved words, `.` and `..` can be assumed to be recognized as reserved keywords and used as reserved names in most cases, 
so I think it is inappropriate to treat them in the same way as other reserved words.
In many cases, users would expect to preserve `.` and `..` as they are, and there is a possibility that the valid file paths are broken if they are replaced.

In the future, another solution may be to add an interface that specifies a callback function to process reserved names.
By customizing this callback function, changing the behavior as you wish will be possible.

**Comment by blerrgh** [comment]
> In many cases, users would expect to preserve `.` and `..` as they are, and there is a possibility that the valid file paths are broken if they are replaced.

I agree that they probably shouldn't be replaced in `sanitize_filepath` since both `.` and `..` are valid in relative paths.  But personally I'm not sure I would expect them to ever be valid via `sanitize_filename` since you cannot name a file `.` or `..`.

I suppose if people are using `sanitize_filename` to check individual path _components_ then they might want to preserve periods.

**Comment by thombashi** [comment]
`pathvalidate v3.2.0` can do the following:

```py
from pathvalidate import sanitize_filename, ValidationError

def add_trailing_underscore(e: ValidationError) -> str:
    if e.reusable_name:
        return e.reserved_name

    return f"{e.reserved_name}_"

sanitize_filename(".", reserved_name_handler=add_trailing_underscore, additional_reserved_names=["."])
```

```
'._'
```
