### ISSUE TITLE
Detect max path and max filename lengths on unix systems

### ISSUE THREAD

**Issue by 7x11x13** [thombashi/pathvalidate#50]
Currently I believe these are hardcoded as 4096 and 255 respectively. It would be better to detect the limits if possible: https://stackoverflow.com/a/62796371

**Comment by 7x11x13** [comment]
I guess this would only work if we are sanitizing for the same platform which we are on. Maybe there could be another platform type "Native" which sanitizes for the platform which the script is being run on?

**Comment by thombashi** [comment]
In the current implementation, if you specify `"auto"` as the `platform` argument, the execution environment will be detected automatically.
https://github.com/thombashi/pathvalidate/blob/92e2f9d3329c8e22c0fcaf59f41517169ebb765d/docs/pages/reference/platform.txt#L6
I think this satisfies your proposed behavior, what do you think?
