### ISSUE TITLE
Update copyright year

### ISSUE THREAD

**Issue by Flimm** [thombashi/pathvalidate#54]
I see on the documentation website this line:

> © Copyright Copyright 2016, Tsuyoshi Hombashi. 

I also see this in `pathvalidate/pathvalidate/__version__.py`:

>     __copyright__ = f"Copyright 2016, {__author__}"

This makes it look like pathvalidate hasn't been updated since 2016. In reality, the latest release on PyPI as of writing is in the year 2023.

When I consider a new dependency, one of the things I look at is its age. This copyright header makes the project look abandoned.

Thank you for making pathvalidate, and I look forward to exploring it!

**Comment by thombashi** [comment]
@Flimm 
Thank you for your feedback.
I updated the copyright year to include the last updated year.
