### ISSUE TITLE
It looks like platform name is not taken into account during sanitization

### ISSUE THREAD

**Issue by julchenok** [thombashi/pathvalidate#7]
Method **sanitize()** in class **FileNameSanitizer** uses **__RE_INVALID_WIN_FILENAME** constant independently from inbound platform name. Shouldn't it check platform and use **__RE_INVALID_FILENAME** in case of non-windows OS?

See code at line:

https://github.com/thombashi/pathvalidate/blob/718e62ad492752f2e5a4307038665c2bc597be26/pathvalidate/_file.py#L122

Similar situation is in **sanitize()** method in **FilePathSanitizer** class:

https://github.com/thombashi/pathvalidate/blob/718e62ad492752f2e5a4307038665c2bc597be26/pathvalidate/_file.py#L212

**Comment by thombashi** [comment]
I had fixed the issue at `pathvalidate 0.23.0`.

**Comment by thombashi** [comment]
I'll close the issue.
Feel free to reopen if you still have any problems about the issue.
