### ISSUE TITLE
CLOCK$ filename on Windows

### ISSUE THREAD

**Issue by sparr** [thombashi/pathvalidate#8]
Per https://en.wikipedia.org/wiki/Filename#Reserved_characters_and_words and various other results on Google, "CLOCK$" is a problematic filename in some versions of Windows. Apparently it is possible to create such a file through some methods, but then not to delete it. Testing on various Windows platforms may reveal more details of the behavior. If it remains problematic, it may warrant inclusion in this library?

**Comment by thombashi** [comment]
@sparr 
Thank you for your report.
That makes sense.
I had added `CLOCK$` as a reserved filename for Windows platform at `pathvalidate 0.25.0`.

**Comment by thombashi** [comment]
I'll close the issue.
Feel free to reopen if you still have any problems about the issue.
